"""empty message

Revision ID: 789913dccc9e
Revises: 097fdeb5c5c8
Create Date: 2018-05-06 22:22:38.036367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789913dccc9e'
down_revision = '097fdeb5c5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'last_updated')
    # ### end Alembic commands ###
