"""empty message

Revision ID: c7f25b92c380
Revises: 69dd2e356f21
Create Date: 2018-05-08 15:29:29.570696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f25b92c380'
down_revision = '69dd2e356f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('broad_category', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'broad_category')
    # ### end Alembic commands ###
