"""empty message

Revision ID: caed57c34937
Revises: c7f25b92c380
Create Date: 2018-05-08 23:11:46.028104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caed57c34937'
down_revision = 'c7f25b92c380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('institution', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'institution')
    # ### end Alembic commands ###
