"""empty message

Revision ID: d08761007e7e
Revises: da6dd5de7b7d
Create Date: 2018-05-03 18:38:38.949287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08761007e7e'
down_revision = 'da6dd5de7b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('category', sa.String(length=5), nullable=True))
    op.add_column('post', sa.Column('demand', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'demand')
    op.drop_column('post', 'category')
    # ### end Alembic commands ###
